// Copyright (c) 2019 Robert Bosch GmbH
// All rights reserved.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.



/*----------------------------------------------------------------------------*/
// The following code is automatically generated by XDK Workbench.
// Copyright (c) BCDS Robert Bosch GmbH
// cf. 3rd-party-licenses.txt file in the root directory of this source tree.

/**
* @ingroup APPS_LIST
*
* @defgroup XDK_APPLICATION_TEMPLATE XDK Application Template
* @{
*
* @brief XDK Application Template
*
* @details Empty XDK Application Template without any functionality. Should be used as a template to start new projects.
*
* @file
**/


/* module includes ********************************************************** */

/* system header files */
#include <stdio.h>
/* additional interface header files */
#include "FreeRTOS.h"
#include "timers.h"
#include "queue.h"
#include "BCDS_CmdProcessor.h"
#include "BCDS_Assert.h"
#include "BCDS_BSP_Board.h"
#include "Serval_HttpClient.h"

/* user header files */
#include "SecureEdgeDevice.h"
#include "CoAPClient.h"
#include "Wifi.h"
#include "Http.h"
#include "SensorData.h"
#include "UserConfig.h"
#include "SystemConfig.h"
#include "Encryption.h"
#include "CoAPServer.h"


/* constant definitions ***************************************************** */

/* local variables ********************************************************** */

/* global variables ********************************************************* */

/* queue handle to exchange data between tasks */
QueueHandle_t dataQueue = NULL;

/*Application Command Processor Instance */
CmdProcessor_T *AppCmdProcessor;

/* inline functions ********************************************************* */

/* local functions ********************************************************** */

/* global functions ********************************************************* */

/**
 * @brief This is a template function where the user can write his custom application.
 *
 */
void appInitSystem(void * CmdProcessorHandle, uint32_t param2)
{
    if (CmdProcessorHandle == NULL) {
        printf("Command processor handle is null \n\r");
        assert(false);
    }

	AppCmdProcessor = (CmdProcessor_T *) CmdProcessorHandle;
    BCDS_UNUSED(param2);

    /* user code */
    Retcode_T ret = RETCODE_FAILURE;
    bool RebootFlag = false;

    /* queue initialization
     * QUEUE_ELEMENT_COUNTER elements each with a size of QUEUE_ELEMENT_SIZE bytes */
    dataQueue = xQueueCreate(QUEUE_ELEMENT_COUNTER, sizeof(queueHandler_T));

    /* Init functions */
#ifdef ENABLE_WIFI
    /* increase size of PA task TASK_STACK_SIZE_SERVALPAL_CMD_PROC to prevent
     * stackoverflow during transmission phase
     */
    ret = WifiNetworkInit();
    if(RETCODE_SUCCESS != ret) {
    	printf("No Wifi connection established\n\r");
    	/* trigger SW reset if something went wrong */
    	BSP_Board_SoftReset();
    }
#endif
#ifdef ENABLE_HTTP
    ret = HttpClient_initialize();
    if(RETCODE_SUCCESS != ret) {
		printf("AppInitSystem: Error in HttpInit\n\r");
		BSP_Board_SoftReset();
	}
#endif
#ifdef ENABLE_SENSOR
    ret = SensorInit();
    if(RETCODE_SUCCESS != ret) {
		printf("AppInitSystem: Error in SensorInit\n\r");
		BSP_Board_SoftReset();
	}
#endif
#ifdef ENABLE_CONSUMER
    ret = CoAPClientInit();
    if(RETCODE_SUCCESS != ret) {
		printf("AppInitSystem: Error in CoAPClientInit\n\r");
		BSP_Board_SoftReset();
	}
#endif
#ifdef ENABLE_PRODUCER
    ret = CoAPServerInit();
    if(RETCODE_SUCCESS != ret) {
		printf("AppInitSystem: Error in CoAPServerInit\n\r");
		BSP_Board_SoftReset();
	}
#endif
#ifdef ENABLE_ENCRYPTION
    ret = InitMbedCrypto();
    if(RETCODE_SUCCESS != ret) {
		printf("AppInitSystem: Error in InitMbedCrypto\n\r");
		BSP_Board_SoftReset();
	}
#endif

/* add user tasks here */
#ifdef ENABLE_WIFI
    if( pdPASS != (xTaskCreate(wifiCyclic, (const char * const) "WifiCheck", 256, NULL, 1, &WifiCheckTask)) )
    {
    	printf("Error xTaskCreate: WifiCheckTask\n\r");
    	BSP_Board_SoftReset();
    	assert(false);
    }
#endif
#if defined(ENABLE_SENSOR) && defined(ENABLE_PRODUCER)
    if( pdPASS != (xTaskCreate(SensorDataCyclic, (const char * const) "Sensor", 512, NULL, 1, &SensorDataTask)) )
    {
    	printf("Error xTaskCreate: SensorDataTask\n\r");
    	BSP_Board_SoftReset();
    	assert(false);
    }
#endif
#ifdef ENABLE_CONSUMER
    if( pdPASS != (xTaskCreate(CoAPClientCyclic, (const char * const) "CoAPCli", 1024, NULL, 1, &CoAPClientTask)) )
    {
    	printf("Error xTaskCreate: CoAPClientTask\n\r");
    	BSP_Board_SoftReset();
    	assert(false);
    }
#endif
#ifdef ENABLE_PRODUCER
    if( pdPASS != (xTaskCreate(prepareSensorPayloadData, (const char * const) "PrepSens", 2048, NULL, 2, &PrepSensPayloadDataTask)) )
    {
    	printf("Error xTaskCreate: prepareSensorPayloadDataTask\n\r");
    	BSP_Board_SoftReset();
    	assert(false);
    }
#endif
#ifdef ENABLE_CONSUMER
    if( pdPASS != (xTaskCreate(processSensorPayloadDataCyclic, (const char * const) "CliSenDat", 2048, NULL, 2, &processSensorPayloadDataTask)) )
    {
    	printf("Error xTaskCreate: HttpNetworkTask\n\r");
    	BSP_Board_SoftReset();
    	assert(false);
    }
#endif
}
/**@} */
/** ************************************************************************* */
