// Copyright (c) 2019 Robert Bosch GmbH
// All rights reserved.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.


/*----------------------------------------------------------------------------*/
// The following code is automatically generated by XDK Workbench.
// Copyright (c) BCDS Robert Bosch GmbH
// cf. 3rd-party-licenses.txt file in the root directory of this source tree.


/**
* @file
* @brief  This Module is Configuration header for XDK Application Template configurations
*
**/

/* header definition ******************************************************** */
#ifndef XDK110_XDKAPPLICATIONTEMPLATE_H_
#define XDK110_XDKAPPLICATIONTEMPLATE_H_

/* user includes */
#include "queue.h"
#include "BCDS_CmdProcessor.h"

/* local interface declaration ********************************************** */
 /* Priorities */
#define TASK_PRIO_MAIN_CMD_PROCESSOR                (UINT32_C(1))
#define TASK_STACK_SIZE_MAIN_CMD_PROCESSOR          (UINT16_C(1024))
#define TASK_Q_LEN_MAIN_CMD_PROCESSOR               (UINT32_C(10))

/* control declaration for external */
extern QueueHandle_t dataQueue;
extern CmdProcessor_T *AppCmdProcessor;

/* local type and macro definitions */

/* local function prototype declarations */

/* local module global variable declarations */

/* local inline function definitions */
/**
 * @brief This is a template function where the user can write his custom application.
 *
 * @param[in] CmdProcessorHandle Handle of the main commandprocessor
 *
 * @param[in] param2  Currently not used will be used in future
 */
void appInitSystem(void * CmdProcessorHandle, uint32_t param2);

#endif /* XDK110_XDKAPPLICATIONTEMPLATE_H_ */

/** ************************************************************************* */
